---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes 
        
  - name: install tmux package
    apt:
      name: tmux
      state: latest

  - name: install vim-nox
    apt:
      name: vim-nox 
      state: latest
