---

- hosts: all
  become: true
  tasks:

  - name: install tmux and vim packages
    package:
      name: 
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
