---

- hosts: all
  become: true
  tasks:

  - name: install tmux and vim packages on debian systems
    apt:
      name: 
        - tmux
        - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution_file_variety == "Debian" 

  - name: install tmux and vim packages on fedora systems
    dnf:
      name:
        - tmux
        - vim
      state: latest
      update_cache: yes
    when: ansible_distribution_file_variety == "RedHat"
